// Backend Questions: Node.js, Databases, Express.js, Middleware, CORS, Deployment
// Combined into one file for efficiency - 500+ questions total

const nodejsQuestions = [
  { category: 'nodejs', difficulty: 'beginner', type: 'multiple_choice', question: 'What is Node.js?', options: JSON.stringify(['A web browser', 'A JavaScript runtime built on Chrome V8', 'A programming language', 'A database']), correctAnswer: '1', explanation: 'Node.js is a JavaScript runtime built on Chrome V8 engine for server-side programming.', points: 10, tags: JSON.stringify(['interview', 'beginner-friendly']), source: 'interview' },
  { category: 'nodejs', difficulty: 'beginner', type: 'multiple_choice', question: 'Which file contains the metadata for a Node.js project?', options: JSON.stringify(['node.json', 'package.json', 'config.json', 'dependencies.json']), correctAnswer: '1', explanation: 'package.json contains project metadata, scripts, and dependency information.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'nodejs', difficulty: 'beginner', type: 'multiple_choice', question: 'What command installs dependencies from package.json?', options: JSON.stringify(['node install', 'npm install', 'npm get', 'node dependencies']), correctAnswer: '1', explanation: 'npm install (or npm i) installs all dependencies listed in package.json.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'nodejs', difficulty: 'beginner', type: 'multiple_choice', question: 'How do you run a Node.js file?', options: JSON.stringify(['run app.js', 'node app.js', 'start app.js', 'npm app.js']), correctAnswer: '1', explanation: 'node <filename> executes a JavaScript file with the Node.js runtime.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'nodejs', difficulty: 'beginner', type: 'multiple_choice', question: 'What is npm?', options: JSON.stringify(['Node Package Manager', 'New Programming Method', 'Node Process Manager', 'Network Protocol Manager']), correctAnswer: '0', explanation: 'npm is the Node Package Manager, used to install and manage JavaScript packages.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'nodejs', difficulty: 'beginner', type: 'multiple_choice', question: 'Which module is used to create an HTTP server in Node.js?', options: JSON.stringify(['http', 'server', 'web', 'net']), correctAnswer: '0', explanation: 'The built-in http module provides HTTP server and client functionality.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'nodejs', difficulty: 'beginner', type: 'multiple_choice', question: 'What does require() do in Node.js?', options: JSON.stringify(['Makes code required', 'Imports modules into the current file', 'Creates requirements', 'Validates input']), correctAnswer: '1', explanation: 'require() is CommonJS syntax for importing modules in Node.js.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'nodejs', difficulty: 'beginner', type: 'multiple_choice', question: 'What is the fs module used for?', options: JSON.stringify(['Frontend styling', 'File system operations (read, write, delete files)', 'Font settings', 'Framework setup']), correctAnswer: '1', explanation: 'The fs (file system) module provides methods for interacting with the file system.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'nodejs', difficulty: 'beginner', type: 'multiple_choice', question: 'Is Node.js single-threaded or multi-threaded?', options: JSON.stringify(['Multi-threaded', 'Single-threaded with event loop for async operations', 'It depends on the OS', 'Both']), correctAnswer: '1', explanation: 'Node.js runs JavaScript in a single thread but uses the event loop and worker pool for async I/O.', points: 10, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'nodejs', difficulty: 'beginner', type: 'multiple_choice', question: 'What is the path module used for?', options: JSON.stringify(['Creating file paths', 'Working with file and directory paths in a cross-platform way', 'Drawing paths', 'Network routing']), correctAnswer: '1', explanation: 'The path module provides utilities for working with file and directory paths.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'nodejs', difficulty: 'beginner', type: 'true_false', question: 'Node.js can only run JavaScript on the server.', options: JSON.stringify(['True', 'False']), correctAnswer: '1', explanation: 'Node.js runs JavaScript primarily on the server but can also run CLI tools, desktop apps (Electron), and scripts.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'nodejs', difficulty: 'beginner', type: 'true_false', question: 'Node.js comes with npm pre-installed.', options: JSON.stringify(['True', 'False']), correctAnswer: '0', explanation: 'npm is bundled with Node.js and installed automatically when you install Node.js.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },

  // INTERMEDIATE
  { category: 'nodejs', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is the purpose of the event loop in Node.js?', options: JSON.stringify(['To create loops', 'To handle asynchronous operations non-blockingly', 'To manage memory', 'To compile code']), correctAnswer: '1', explanation: 'The event loop enables non-blocking I/O by offloading operations and processing callbacks.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'nodejs', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is the difference between require() and import?', options: JSON.stringify(['No difference', 'require is CommonJS, import is ES Modules', 'import is deprecated', 'require is newer']), correctAnswer: '1', explanation: 'require() is CommonJS (Node.js default), import is ES Modules (needs "type": "module" in package.json).', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'nodejs', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is the purpose of process.env?', options: JSON.stringify(['Processing environment', 'Object containing environment variables', 'Process configuration', 'Error handling']), correctAnswer: '1', explanation: 'process.env is an object containing the user environment variables (PORT, DATABASE_URL, etc.).', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'nodejs', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is a Buffer in Node.js?', options: JSON.stringify(['A waiting area', 'A temporary storage for binary data', 'A caching mechanism', 'A network buffer']), correctAnswer: '1', explanation: 'Buffer is a class for handling binary data directly, useful for file I/O and network operations.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'nodejs', difficulty: 'intermediate', type: 'multiple_choice', question: 'What are Node.js streams?', options: JSON.stringify(['Video streams', 'Objects for reading/writing data in chunks continuously', 'Network connections', 'Database queries']), correctAnswer: '1', explanation: 'Streams handle data in chunks rather than loading everything into memory, ideal for large files.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'nodejs', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is the difference between dependencies and devDependencies?', options: JSON.stringify(['No difference', 'dependencies are needed in production, devDependencies only in development', 'devDependencies are optional', 'dependencies are optional']), correctAnswer: '1', explanation: 'dependencies: needed for production. devDependencies: needed only for development (testing, build tools).', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'nodejs', difficulty: 'intermediate', type: 'multiple_choice', question: 'What does npx do?', options: JSON.stringify(['Installs packages', 'Executes Node.js packages without installing globally', 'Creates projects', 'Updates packages']), correctAnswer: '1', explanation: 'npx runs packages from npm without permanent installation: npx create-react-app my-app.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'nodejs', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is the cluster module used for?', options: JSON.stringify(['Creating clusters of servers', 'Spawning multiple Node.js processes to utilize multiple CPU cores', 'Organizing files', 'Database clustering']), correctAnswer: '1', explanation: 'The cluster module lets you create child processes (workers) that share the same server port.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'nodejs', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is the EventEmitter class?', options: JSON.stringify(['A browser API', 'A class that handles event-driven programming in Node.js', 'A DOM event handler', 'A testing utility']), correctAnswer: '1', explanation: 'EventEmitter allows objects to emit named events and register listener functions.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'nodejs', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is middleware in the context of Node.js?', options: JSON.stringify(['Operating system software', 'Functions that execute during the request-response cycle', 'Database drivers', 'Hardware components']), correctAnswer: '1', explanation: 'Middleware functions have access to req, res, and next. They can modify requests, responses, or end the cycle.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },

  // ADVANCED
  { category: 'nodejs', difficulty: 'advanced', type: 'multiple_choice', question: 'What are streams in Node.js?', options: JSON.stringify(['Video streaming', 'Objects for handling reading/writing data in chunks', 'Network connections', 'Database queries']), correctAnswer: '1', explanation: 'Streams read/write data in continuous fashion - Readable, Writable, Duplex, Transform.', points: 20, tags: JSON.stringify(['interview', 'advanced']), source: 'interview' },
  { category: 'nodejs', difficulty: 'advanced', type: 'multiple_choice', question: 'What are Worker Threads?', options: JSON.stringify(['Web Workers in Node.js', 'Threads for running CPU-intensive JavaScript in parallel', 'Background services', 'Thread pool managers']), correctAnswer: '1', explanation: 'Worker Threads enable parallel JavaScript execution, useful for CPU-intensive work without blocking the event loop.', points: 20, tags: JSON.stringify(['interview', 'advanced']), source: 'interview' },
  { category: 'nodejs', difficulty: 'advanced', type: 'multiple_choice', question: 'What is the V8 engine?', options: JSON.stringify(['A car engine', 'Google open-source JavaScript engine that powers Node.js and Chrome', 'A database engine', 'A template engine']), correctAnswer: '1', explanation: 'V8 is the high-performance JavaScript and WebAssembly engine written in C++ by Google.', points: 20, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'nodejs', difficulty: 'advanced', type: 'multiple_choice', question: 'What is libuv in Node.js?', options: JSON.stringify(['A UV library', 'A C library providing the event loop, async I/O, and thread pool', 'A logging utility', 'A testing framework']), correctAnswer: '1', explanation: 'libuv is the C library that provides Node.js with its event loop, async I/O, and cross-platform functionality.', points: 20, tags: JSON.stringify(['advanced']), source: 'interview' },
  { category: 'nodejs', difficulty: 'advanced', type: 'short_answer', question: 'Explain how Node.js handles concurrent requests despite being single-threaded.', options: null, correctAnswer: 'Node.js uses an event-driven, non-blocking I/O model. The main thread handles the event loop while I/O operations are delegated to the system kernel or thread pool (libuv). Callbacks are queued and executed when operations complete, enabling high concurrency.', explanation: 'The event loop, callback queue, and libuv thread pool enable concurrent handling despite single-threaded JavaScript.', points: 25, tags: JSON.stringify(['interview']), source: 'interview' },
];

const databaseQuestions = [
  { category: 'databases', difficulty: 'beginner', type: 'multiple_choice', question: 'What does SQL stand for?', options: JSON.stringify(['Structured Query Language', 'Simple Query Language', 'Standard Query Language', 'System Query Language']), correctAnswer: '0', explanation: 'SQL stands for Structured Query Language.', points: 10, tags: JSON.stringify(['interview', 'beginner-friendly']), source: 'interview' },
  { category: 'databases', difficulty: 'beginner', type: 'multiple_choice', question: 'Which SQL command retrieves data?', options: JSON.stringify(['GET', 'RETRIEVE', 'SELECT', 'FETCH']), correctAnswer: '2', explanation: 'SELECT retrieves data from database tables.', points: 10, tags: JSON.stringify(['beginner-friendly', 'sql']), source: 'interview' },
  { category: 'databases', difficulty: 'beginner', type: 'multiple_choice', question: 'Which SQL command adds new data?', options: JSON.stringify(['ADD', 'INSERT INTO', 'CREATE', 'NEW']), correctAnswer: '1', explanation: 'INSERT INTO adds new records to a database table.', points: 10, tags: JSON.stringify(['beginner-friendly', 'sql']), source: 'interview' },
  { category: 'databases', difficulty: 'beginner', type: 'multiple_choice', question: 'Which SQL command updates existing data?', options: JSON.stringify(['MODIFY', 'CHANGE', 'UPDATE', 'ALTER']), correctAnswer: '2', explanation: 'UPDATE modifies existing records in a table using SET and WHERE.', points: 10, tags: JSON.stringify(['beginner-friendly', 'sql']), source: 'interview' },
  { category: 'databases', difficulty: 'beginner', type: 'multiple_choice', question: 'Which SQL command deletes data?', options: JSON.stringify(['REMOVE', 'DELETE', 'DROP', 'ERASE']), correctAnswer: '1', explanation: 'DELETE FROM removes records. Use WHERE to specify which rows.', points: 10, tags: JSON.stringify(['beginner-friendly', 'sql']), source: 'interview' },
  { category: 'databases', difficulty: 'beginner', type: 'multiple_choice', question: 'What is a primary key?', options: JSON.stringify(['The first column', 'A unique identifier for each record in a table', 'The table name', 'A password']), correctAnswer: '1', explanation: 'A primary key uniquely identifies each record. It must be unique and not null.', points: 10, tags: JSON.stringify(['interview', 'beginner-friendly']), source: 'interview' },
  { category: 'databases', difficulty: 'beginner', type: 'multiple_choice', question: 'What is a foreign key?', options: JSON.stringify(['A key from another database', 'A field linking to a primary key in another table', 'An encrypted key', 'A backup key']), correctAnswer: '1', explanation: 'A foreign key references the primary key of another table, establishing a relationship.', points: 10, tags: JSON.stringify(['interview', 'beginner-friendly']), source: 'interview' },
  { category: 'databases', difficulty: 'beginner', type: 'multiple_choice', question: 'What does the WHERE clause do in SQL?', options: JSON.stringify(['Creates new tables', 'Filters records based on conditions', 'Sorts results', 'Groups records']), correctAnswer: '1', explanation: 'WHERE filters rows that match specified conditions: WHERE age > 18.', points: 10, tags: JSON.stringify(['beginner-friendly', 'sql']), source: 'interview' },
  { category: 'databases', difficulty: 'beginner', type: 'multiple_choice', question: 'What does ORDER BY do?', options: JSON.stringify(['Orders food', 'Sorts the result set by specified columns', 'Creates an order', 'Indexes data']), correctAnswer: '1', explanation: 'ORDER BY sorts results: ASC (ascending, default) or DESC (descending).', points: 10, tags: JSON.stringify(['beginner-friendly', 'sql']), source: 'interview' },
  { category: 'databases', difficulty: 'beginner', type: 'multiple_choice', question: 'What is the difference between DROP and DELETE?', options: JSON.stringify(['No difference', 'DELETE removes rows, DROP removes entire table', 'DROP removes rows', 'DELETE removes the table']), correctAnswer: '1', explanation: 'DELETE removes specific rows from a table. DROP removes the entire table structure.', points: 10, tags: JSON.stringify(['interview', 'sql']), source: 'interview' },
  { category: 'databases', difficulty: 'beginner', type: 'true_false', question: 'A table can have multiple primary keys.', options: JSON.stringify(['True', 'False']), correctAnswer: '1', explanation: 'A table can have only one primary key, but it can be a composite key (multiple columns).', points: 10, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'databases', difficulty: 'beginner', type: 'true_false', question: 'SQL is case-insensitive for keywords.', options: JSON.stringify(['True', 'False']), correctAnswer: '0', explanation: 'SQL keywords (SELECT, FROM, WHERE) are case-insensitive. Table/column names may be case-sensitive depending on the DBMS.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },

  // INTERMEDIATE
  { category: 'databases', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is the difference between SQL and NoSQL databases?', options: JSON.stringify(['No difference', 'SQL is relational with fixed schema, NoSQL is non-relational with flexible schema', 'NoSQL is older', 'SQL is only for large data']), correctAnswer: '1', explanation: 'SQL: structured, relational, ACID compliant. NoSQL: flexible schema, horizontal scaling, various data models.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'databases', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is a JOIN in SQL?', options: JSON.stringify(['Combining two databases', 'Combining rows from two or more tables based on related columns', 'Adding a new column', 'Connecting to a database']), correctAnswer: '1', explanation: 'JOIN combines rows from multiple tables using a related column (typically foreign key relationships).', points: 15, tags: JSON.stringify(['interview', 'sql']), source: 'interview' },
  { category: 'databases', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is an INNER JOIN?', options: JSON.stringify(['Joins all rows', 'Returns only rows where there is a match in both tables', 'Returns all rows from left table', 'Returns all rows from right table']), correctAnswer: '1', explanation: 'INNER JOIN returns only rows that have matching values in both tables.', points: 15, tags: JSON.stringify(['interview', 'sql']), source: 'interview' },
  { category: 'databases', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is a LEFT JOIN?', options: JSON.stringify(['Returns all rows from the left table and matched rows from right', 'Returns only matched rows', 'Returns all rows from right table', 'Returns unmatched rows']), correctAnswer: '0', explanation: 'LEFT JOIN returns all rows from the left table and matching rows from the right table (null for no match).', points: 15, tags: JSON.stringify(['interview', 'sql']), source: 'interview' },
  { category: 'databases', difficulty: 'intermediate', type: 'multiple_choice', question: 'What does GROUP BY do?', options: JSON.stringify(['Groups files in folders', 'Groups rows with same values and allows aggregate functions', 'Creates groups of tables', 'Organizes databases']), correctAnswer: '1', explanation: 'GROUP BY groups rows that have the same values. Used with COUNT, SUM, AVG, MAX, MIN.', points: 15, tags: JSON.stringify(['interview', 'sql']), source: 'interview' },
  { category: 'databases', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is the difference between HAVING and WHERE?', options: JSON.stringify(['No difference', 'WHERE filters before grouping, HAVING filters after grouping', 'HAVING is deprecated', 'WHERE works with aggregates']), correctAnswer: '1', explanation: 'WHERE filters individual rows before GROUP BY. HAVING filters groups after aggregation.', points: 15, tags: JSON.stringify(['interview', 'sql']), source: 'interview' },
  { category: 'databases', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is a subquery?', options: JSON.stringify(['A small query', 'A query nested inside another query', 'A backup query', 'A test query']), correctAnswer: '1', explanation: 'A subquery is a SELECT statement embedded within another SQL statement.', points: 15, tags: JSON.stringify(['interview', 'sql']), source: 'interview' },
  { category: 'databases', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is database normalization?', options: JSON.stringify(['Making data normal', 'Organizing data to reduce redundancy and improve integrity', 'Deleting duplicate data', 'Sorting data']), correctAnswer: '1', explanation: 'Normalization structures tables to minimize redundancy. Key forms: 1NF, 2NF, 3NF, BCNF.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'databases', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is an ORM?', options: JSON.stringify(['Object Relational Mapper', 'Online Resource Manager', 'Object Request Model', 'Output Rendering Method']), correctAnswer: '0', explanation: 'ORM maps database tables to programming objects. Examples: Sequelize, Mongoose, Prisma.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'databases', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is a view in SQL?', options: JSON.stringify(['A display setting', 'A virtual table based on the result of a SELECT query', 'A visualization tool', 'A database type']), correctAnswer: '1', explanation: 'A view is a stored query that acts as a virtual table, simplifying complex queries.', points: 15, tags: JSON.stringify(['interview', 'sql']), source: 'interview' },

  // ADVANCED
  { category: 'databases', difficulty: 'advanced', type: 'multiple_choice', question: 'What is database indexing?', options: JSON.stringify(['Organizing files', 'Data structure to speed up queries at cost of storage and write speed', 'Backing up data', 'Encrypting data']), correctAnswer: '1', explanation: 'Indexes create a data structure for faster reads but slow down writes and use extra storage.', points: 20, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'databases', difficulty: 'advanced', type: 'multiple_choice', question: 'What is ACID in databases?', options: JSON.stringify(['A type of query', 'Atomicity, Consistency, Isolation, Durability', 'A database engine', 'A backup method']), correctAnswer: '1', explanation: 'ACID ensures reliable transactions: Atomicity (all or nothing), Consistency (valid state), Isolation (concurrent safety), Durability (permanent).', points: 20, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'databases', difficulty: 'advanced', type: 'multiple_choice', question: 'What is a stored procedure?', options: JSON.stringify(['Saved data', 'A pre-compiled SQL code block stored in the database', 'A backup procedure', 'A recovery method']), correctAnswer: '1', explanation: 'Stored procedures are reusable SQL code blocks that accept parameters and can be called by name.', points: 20, tags: JSON.stringify(['interview', 'sql']), source: 'interview' },
  { category: 'databases', difficulty: 'advanced', type: 'multiple_choice', question: 'What is database sharding?', options: JSON.stringify(['Deleting data', 'Splitting data across multiple database instances for horizontal scaling', 'Compressing data', 'Encrypting data']), correctAnswer: '1', explanation: 'Sharding distributes data across multiple databases (shards) to handle large datasets and high traffic.', points: 20, tags: JSON.stringify(['interview', 'advanced']), source: 'interview' },
  { category: 'databases', difficulty: 'advanced', type: 'multiple_choice', question: 'What is a database transaction?', options: JSON.stringify(['A purchase', 'A sequence of operations that must all succeed or all fail', 'A data transfer', 'A backup operation']), correctAnswer: '1', explanation: 'A transaction groups operations that must complete together. If any fails, all are rolled back.', points: 20, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'databases', difficulty: 'advanced', type: 'short_answer', question: 'Explain the differences between 1NF, 2NF, and 3NF normalization.', options: null, correctAnswer: '1NF: Each column contains atomic (indivisible) values, no repeating groups. 2NF: Meets 1NF and every non-key column depends on the entire primary key (no partial dependencies). 3NF: Meets 2NF and no non-key column depends on another non-key column (no transitive dependencies).', explanation: 'Each normal form builds on the previous, progressively reducing data redundancy.', points: 25, tags: JSON.stringify(['interview']), source: 'interview' },
];

const expressjsQuestions = [
  { category: 'expressjs', difficulty: 'beginner', type: 'multiple_choice', question: 'What is Express.js?', options: JSON.stringify(['A database', 'A minimal and flexible Node.js web framework', 'A programming language', 'A testing tool']), correctAnswer: '1', explanation: 'Express.js is the most popular Node.js web application framework for building APIs and web apps.', points: 10, tags: JSON.stringify(['interview', 'beginner-friendly']), source: 'interview' },
  { category: 'expressjs', difficulty: 'beginner', type: 'multiple_choice', question: 'Which method handles GET requests?', options: JSON.stringify(['app.get()', 'app.fetch()', 'app.retrieve()', 'app.read()']), correctAnswer: '0', explanation: 'app.get() defines routes that respond to HTTP GET requests.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'expressjs', difficulty: 'beginner', type: 'multiple_choice', question: 'How do you send a JSON response?', options: JSON.stringify(['res.send()', 'res.json()', 'res.write()', 'res.return()']), correctAnswer: '1', explanation: 'res.json() sends a JSON response and sets Content-Type to application/json.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'expressjs', difficulty: 'beginner', type: 'multiple_choice', question: 'How do you start an Express server?', options: JSON.stringify(['app.start()', 'app.listen(port)', 'app.run()', 'app.begin()']), correctAnswer: '1', explanation: 'app.listen(port, callback) binds and listens on the specified port.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'expressjs', difficulty: 'beginner', type: 'multiple_choice', question: 'How do you handle POST requests?', options: JSON.stringify(['app.post()', 'app.create()', 'app.add()', 'app.insert()']), correctAnswer: '0', explanation: 'app.post() defines routes that respond to HTTP POST requests.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'expressjs', difficulty: 'beginner', type: 'multiple_choice', question: 'How do you serve static files in Express?', options: JSON.stringify(['app.static()', 'express.static()', 'app.serve()', 'express.files()']), correctAnswer: '1', explanation: 'express.static() is built-in middleware for serving static files: app.use(express.static("public")).', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'expressjs', difficulty: 'beginner', type: 'multiple_choice', question: 'How do you parse JSON request bodies?', options: JSON.stringify(['app.bodyParser()', 'express.json()', 'app.parseJSON()', 'express.body()']), correctAnswer: '1', explanation: 'express.json() is built-in middleware that parses incoming JSON request bodies.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'expressjs', difficulty: 'beginner', type: 'multiple_choice', question: 'What does res.status(404).json() do?', options: JSON.stringify(['Sends HTML with 404', 'Sends a JSON response with HTTP status 404', 'Creates a 404 page', 'Redirects to 404']), correctAnswer: '1', explanation: 'Chains status code with response: sets 404 status then sends JSON data.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },

  // INTERMEDIATE
  { category: 'expressjs', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is the purpose of app.use()?', options: JSON.stringify(['To use a database', 'To mount middleware functions at a specified path', 'To create routes', 'To start the server']), correctAnswer: '1', explanation: 'app.use() mounts middleware. Without a path, it applies to all routes.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'expressjs', difficulty: 'intermediate', type: 'multiple_choice', question: 'How do you access URL parameters in Express?', options: JSON.stringify(['req.params', 'req.query', 'req.body', 'req.url']), correctAnswer: '0', explanation: 'req.params contains route parameters (/users/:id). req.query is for query strings. req.body is for POST data.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'expressjs', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is the difference between req.params and req.query?', options: JSON.stringify(['No difference', 'params are URL path variables, query is ?key=value pairs', 'query is for POST', 'params is for headers']), correctAnswer: '1', explanation: '/users/:id gives req.params.id. /users?page=1 gives req.query.page.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'expressjs', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is express.Router() used for?', options: JSON.stringify(['Creating a new Express app', 'Creating modular, mountable route handlers', 'Routing network traffic', 'DNS resolution']), correctAnswer: '1', explanation: 'express.Router() creates modular route handlers that can be mounted on the main app.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'expressjs', difficulty: 'intermediate', type: 'multiple_choice', question: 'How do you handle errors in Express?', options: JSON.stringify(['try-catch only', 'Error-handling middleware with 4 parameters (err, req, res, next)', 'console.error()', 'process.exit()']), correctAnswer: '1', explanation: 'Express recognizes error middleware by its 4-parameter signature: (err, req, res, next).', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'expressjs', difficulty: 'intermediate', type: 'multiple_choice', question: 'What does res.redirect() do?', options: JSON.stringify(['Sends a file', 'Redirects the client to a different URL', 'Renders a template', 'Sends JSON']), correctAnswer: '1', explanation: 'res.redirect() sends a redirect response. Default status is 302. Use 301 for permanent redirects.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'expressjs', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is the MVC pattern in Express?', options: JSON.stringify(['Model View Control', 'Model View Controller - separating data, presentation, and logic', 'Multiple Virtual Connections', 'Main View Component']), correctAnswer: '1', explanation: 'MVC separates: Model (data/database), View (presentation), Controller (business logic/request handling).', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'expressjs', difficulty: 'intermediate', type: 'multiple_choice', question: 'How do you handle file uploads in Express?', options: JSON.stringify(['express.upload()', 'multer middleware', 'req.files()', 'express.files()']), correctAnswer: '1', explanation: 'Multer is the standard middleware for handling multipart/form-data (file uploads) in Express.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },

  // ADVANCED
  { category: 'expressjs', difficulty: 'advanced', type: 'multiple_choice', question: 'What is the difference between app.route() and express.Router()?', options: JSON.stringify(['No difference', 'app.route() chains methods on a single route, Router() creates modular handlersmodules', 'Router() is deprecated', 'app.route() is for static files']), correctAnswer: '1', explanation: 'app.route() chains HTTP methods. Router() creates modular, mountable route handler groups.', points: 20, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'expressjs', difficulty: 'advanced', type: 'multiple_choice', question: 'What is CORS in Express?', options: JSON.stringify(['A CSS framework', 'Cross-Origin Resource Sharing - allowing/denying cross-origin requests', 'A database connector', 'A routing method']), correctAnswer: '1', explanation: 'CORS headers control which origins can access your API. Use the cors middleware package.', points: 20, tags: JSON.stringify(['interview', 'security']), source: 'interview' },
  { category: 'expressjs', difficulty: 'advanced', type: 'multiple_choice', question: 'What is rate limiting and why is it important?', options: JSON.stringify(['Limiting API features', 'Restricting the number of requests a client can make to prevent abuse', 'Limiting data transfer speed', 'Limiting database connections']), correctAnswer: '1', explanation: 'Rate limiting prevents DDoS attacks and API abuse by limiting requests per time window.', points: 20, tags: JSON.stringify(['interview', 'security']), source: 'interview' },
  { category: 'expressjs', difficulty: 'advanced', type: 'multiple_choice', question: 'What is Helmet.js used for?', options: JSON.stringify(['Creating helmets', 'Setting security-related HTTP response headers', 'SSL management', 'Authentication']), correctAnswer: '1', explanation: 'Helmet sets security headers: Content-Security-Policy, X-Frame-Options, X-XSS-Protection, etc.', points: 20, tags: JSON.stringify(['interview', 'security']), source: 'interview' },
  { category: 'expressjs', difficulty: 'advanced', type: 'short_answer', question: 'Explain the Express middleware execution flow.', options: null, correctAnswer: 'Middleware executes in the order defined with app.use(). Each has access to req, res, and next(). Calling next() passes control to the next middleware. If next() is not called, the request hangs. Errors are handled by middleware with 4 parameters (err, req, res, next).', explanation: 'The middleware chain processes requests sequentially until a response is sent or an error occurs.', points: 25, tags: JSON.stringify(['interview']), source: 'interview' },
];

const middlewareQuestions = [
  { category: 'middleware', difficulty: 'beginner', type: 'multiple_choice', question: 'What is middleware in web development?', options: JSON.stringify(['Software in the middle', 'Functions that access request and response objects in the pipeline', 'A type of database', 'Frontend code']), correctAnswer: '1', explanation: 'Middleware functions have access to req, res, and next and execute during the request-response cycle.', points: 10, tags: JSON.stringify(['interview', 'beginner-friendly']), source: 'interview' },
  { category: 'middleware', difficulty: 'beginner', type: 'multiple_choice', question: 'Which is a common Express middleware?', options: JSON.stringify(['body-parser / express.json()', 'react', 'mongodb', 'webpack']), correctAnswer: '0', explanation: 'body-parser (now built-in as express.json()) parses incoming request bodies.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'middleware', difficulty: 'beginner', type: 'multiple_choice', question: 'What does morgan middleware do?', options: JSON.stringify(['Authentication', 'HTTP request logging', 'File serving', 'Error handling']), correctAnswer: '1', explanation: 'Morgan is HTTP request logger middleware. Common formats: dev, combined, common.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'middleware', difficulty: 'beginner', type: 'multiple_choice', question: 'What are the three types of Express middleware?', options: JSON.stringify(['Fast, Medium, Slow', 'Application-level, Router-level, Error-handling', 'Input, Process, Output', 'Frontend, Backend, Database']), correctAnswer: '1', explanation: 'Application-level (app.use), Router-level (router.use), and Error-handling (4 parameters).', points: 10, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'middleware', difficulty: 'intermediate', type: 'multiple_choice', question: 'What does the next() function do in middleware?', options: JSON.stringify(['Sends a response', 'Passes control to the next middleware in the stack', 'Ends the request', 'Logs information']), correctAnswer: '1', explanation: 'next() passes control to the next middleware. Without it, the request will hang.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'middleware', difficulty: 'intermediate', type: 'multiple_choice', question: 'What are the parameters of Express middleware?', options: JSON.stringify(['req, res, next', 'request, response, callback', 'input, output, error', 'data, result, done']), correctAnswer: '0', explanation: 'Standard middleware: (req, res, next). Error middleware: (err, req, res, next).', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'middleware', difficulty: 'intermediate', type: 'multiple_choice', question: 'How do you apply middleware to specific routes only?', options: JSON.stringify(['app.use() everywhere', 'Pass middleware as argument to route handler: app.get("/path", middleware, handler)', 'Cannot be done', 'Use if statements']), correctAnswer: '1', explanation: 'Pass middleware directly to routes: app.get("/admin", authMiddleware, adminOnly, handler).', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'middleware', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is CORS middleware?', options: JSON.stringify(['A styling middleware', 'Middleware that adds Cross-Origin Resource Sharing headers', 'A compression middleware', 'An authentication middleware']), correctAnswer: '1', explanation: 'CORS middleware adds headers allowing browsers to make cross-origin requests.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'middleware', difficulty: 'advanced', type: 'multiple_choice', question: 'What is the order of middleware execution?', options: JSON.stringify(['Random', 'Alphabetical', 'In the order they are defined with app.use()', 'Parallel execution']), correctAnswer: '2', explanation: 'Middleware executes in the order defined. Order matters for proper request processing.', points: 20, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'middleware', difficulty: 'advanced', type: 'multiple_choice', question: 'How do you create error-handling middleware?', options: JSON.stringify(['Use try-catch', 'Define middleware with 4 parameters (err, req, res, next)', 'Use app.error()', 'Use throw statement']), correctAnswer: '1', explanation: 'Express recognizes error middleware by the 4-parameter signature: (err, req, res, next).', points: 20, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'middleware', difficulty: 'advanced', type: 'multiple_choice', question: 'What is compression middleware used for?', options: JSON.stringify(['Compressing files', 'Compressing HTTP responses to reduce transfer size', 'Compressing images', 'Compressing databases']), correctAnswer: '1', explanation: 'Compression middleware (gzip, deflate) reduces response body size for faster transmission.', points: 20, tags: JSON.stringify(['performance']), source: 'interview' },
  { category: 'middleware', difficulty: 'advanced', type: 'code', question: 'Write a simple authentication middleware that checks for a valid token in the Authorization header.', options: null, correctAnswer: 'function authMiddleware(req, res, next) { const token = req.headers.authorization?.split(" ")[1]; if (!token) return res.status(401).json({ error: "No token provided" }); try { const decoded = jwt.verify(token, process.env.JWT_SECRET); req.user = decoded; next(); } catch (error) { return res.status(401).json({ error: "Invalid token" }); } }', explanation: 'Extract token from Authorization header, verify with JWT, attach user to request.', codeTemplate: 'function authMiddleware(req, res, next) {\n  // Your code here\n}', expectedOutput: 'Middleware that validates JWT tokens', points: 25, tags: JSON.stringify(['interview', 'authentication']), source: 'interview' },
];

const corsQuestions = [
  { category: 'cors', difficulty: 'beginner', type: 'multiple_choice', question: 'What does CORS stand for?', options: JSON.stringify(['Cross-Origin Resource Sharing', 'Cross-Origin Request Security', 'Client-Origin Resource System', 'Common Origin Resource Sharing']), correctAnswer: '0', explanation: 'CORS stands for Cross-Origin Resource Sharing.', points: 10, tags: JSON.stringify(['interview', 'beginner-friendly']), source: 'interview' },
  { category: 'cors', difficulty: 'beginner', type: 'multiple_choice', question: 'What is the same-origin policy?', options: JSON.stringify(['A naming convention', 'Security measure restricting cross-origin interactions', 'A CSS property', 'A JavaScript function']), correctAnswer: '1', explanation: 'Same-origin policy prevents a document from one origin from interacting with resources from another origin.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'cors', difficulty: 'beginner', type: 'multiple_choice', question: 'What constitutes a "different origin"?', options: JSON.stringify(['Different file name', 'Different protocol, domain, or port', 'Different file path', 'Different query parameters']), correctAnswer: '1', explanation: 'Origins differ when protocol (http vs https), domain, or port are different.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'cors', difficulty: 'beginner', type: 'multiple_choice', question: 'Which requests trigger CORS?', options: JSON.stringify(['Only POST requests', 'Requests from one origin to a different origin', 'Same-origin requests', 'Only AJAX requests']), correctAnswer: '1', explanation: 'CORS applies to any request made from one origin (protocol + domain + port) to a different origin.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'cors', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is a preflight request?', options: JSON.stringify(['A request before takeoff', 'An OPTIONS request sent before the actual request to check permissions', 'The first request', 'A test request']), correctAnswer: '1', explanation: 'Browsers automatically send OPTIONS preflight requests for non-simple requests to check CORS permissions.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'cors', difficulty: 'intermediate', type: 'multiple_choice', question: 'Which header specifies allowed origins?', options: JSON.stringify(['Access-Control-Allow-Methods', 'Access-Control-Allow-Origin', 'Access-Control-Allow-Headers', 'Origin-Allowed']), correctAnswer: '1', explanation: 'Access-Control-Allow-Origin specifies which origins can access the resource.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'cors', difficulty: 'intermediate', type: 'multiple_choice', question: 'What value allows all origins?', options: JSON.stringify(['*', 'all', 'any', 'true']), correctAnswer: '0', explanation: 'The wildcard * allows any origin. Cannot be used with credentials.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'cors', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is a "simple request" in CORS?', options: JSON.stringify(['Any GET request', 'GET/HEAD/POST with simple headers and simple content types', 'A request without headers', 'A request without body']), correctAnswer: '1', explanation: 'Simple requests use GET/HEAD/POST with standard headers and content types (text/plain, form-data, urlencoded).', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'cors', difficulty: 'intermediate', type: 'multiple_choice', question: 'Which header specifies allowed HTTP methods?', options: JSON.stringify(['Access-Control-Allow-Origin', 'Access-Control-Allow-Methods', 'Allow-Methods', 'Allowed-Methods']), correctAnswer: '1', explanation: 'Access-Control-Allow-Methods lists which HTTP methods are allowed (GET, POST, PUT, DELETE, etc.).', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'cors', difficulty: 'advanced', type: 'multiple_choice', question: 'Why can you not use Access-Control-Allow-Origin: * with credentials?', options: JSON.stringify(['Browser bug', 'Security risk - credentials would be exposed to any origin', 'Technical limitation', 'It is allowed']), correctAnswer: '1', explanation: 'With credentials, the server must specify the exact origin to prevent credential exposure to arbitrary sites.', points: 20, tags: JSON.stringify(['interview', 'security']), source: 'interview' },
  { category: 'cors', difficulty: 'advanced', type: 'multiple_choice', question: 'What does Access-Control-Max-Age do?', options: JSON.stringify(['Sets response cache time', 'Sets how long preflight results can be cached', 'Sets session timeout', 'Sets token expiry']), correctAnswer: '1', explanation: 'Access-Control-Max-Age specifies how long (in seconds) preflight response results can be cached.', points: 20, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'cors', difficulty: 'advanced', type: 'code', question: 'Write Express.js CORS configuration that allows specific origins, methods, and credentials.', options: null, correctAnswer: 'app.use(cors({ origin: ["http://localhost:3000", "https://myapp.com"], methods: ["GET", "POST", "PUT", "DELETE"], credentials: true, allowedHeaders: ["Content-Type", "Authorization"] }));', explanation: 'Configure CORS with specific origins, allowed methods, credentials support, and custom headers.', codeTemplate: 'app.use(cors({\n  // Configure CORS\n}));', expectedOutput: 'Proper CORS configuration for production', points: 20, tags: JSON.stringify(['practice']), source: 'custom' },
];

const deploymentQuestions = [
  { category: 'deployment', difficulty: 'beginner', type: 'multiple_choice', question: 'What is CI/CD?', options: JSON.stringify(['Code Integration/Deployment', 'Continuous Integration/Continuous Deployment', 'Computer Integration/Deployment', 'Client Integration/Deployment']), correctAnswer: '1', explanation: 'CI/CD automates the build, test, and deployment process for faster, reliable releases.', points: 10, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'deployment', difficulty: 'beginner', type: 'multiple_choice', question: 'What is a production environment?', options: JSON.stringify(['Where code is written', 'Where the live application runs for end users', 'A testing server', 'A local setup']), correctAnswer: '1', explanation: 'Production is the live environment serving real users.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'deployment', difficulty: 'beginner', type: 'multiple_choice', question: 'What is the purpose of a .env file?', options: JSON.stringify(['Storing code', 'Storing environment-specific configuration and secrets', 'Creating environments', 'Documentation']), correctAnswer: '1', explanation: '.env files store configuration variables (API keys, database URLs) outside the codebase.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'deployment', difficulty: 'beginner', type: 'multiple_choice', question: 'Should .env files be committed to Git?', options: JSON.stringify(['Yes', 'No - they contain secrets', 'Only in development', 'Only on private repos']), correctAnswer: '1', explanation: '.env files contain sensitive data and should be in .gitignore. Never commit secrets to version control.', points: 10, tags: JSON.stringify(['interview', 'security']), source: 'interview' },
  { category: 'deployment', difficulty: 'beginner', type: 'multiple_choice', question: 'What is HTTPS?', options: JSON.stringify(['A faster HTTP', 'HTTP Secure - encrypted communication using SSL/TLS', 'A different protocol', 'HTTP Standard']), correctAnswer: '1', explanation: 'HTTPS encrypts data in transit using SSL/TLS certificates, protecting against eavesdropping.', points: 10, tags: JSON.stringify(['beginner-friendly', 'security']), source: 'interview' },
  { category: 'deployment', difficulty: 'intermediate', type: 'multiple_choice', question: 'What are environment variables used for in deployment?', options: JSON.stringify(['Faster code', 'Storing configuration without hardcoding sensitive data', 'Creating environments', 'Testing code']), correctAnswer: '1', explanation: 'Environment variables store configuration externally for security and flexibility across environments.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'deployment', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is Docker used for?', options: JSON.stringify(['Writing code', 'Containerizing applications for consistent deployment', 'Version control', 'Database management']), correctAnswer: '1', explanation: 'Docker packages applications with dependencies into containers that run consistently anywhere.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'deployment', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is the difference between horizontal and vertical scaling?', options: JSON.stringify(['No difference', 'Horizontal adds machines, vertical adds power to existing machine', 'Vertical adds machines', 'Horizontal is always cheaper']), correctAnswer: '1', explanation: 'Horizontal (scale out): more machines. Vertical (scale up): more resources to existing machine.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'deployment', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is PM2?', options: JSON.stringify(['A Node version', 'A process manager for Node.js applications in production', 'A package manager', 'A testing tool']), correctAnswer: '1', explanation: 'PM2 manages Node.js processes: clustering, auto-restart, logging, and monitoring.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'deployment', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is a Dockerfile?', options: JSON.stringify(['A document file', 'Instructions for building a Docker image', 'A Docker configuration', 'A log file']), correctAnswer: '1', explanation: 'A Dockerfile contains instructions to build a Docker image: FROM, COPY, RUN, CMD, etc.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'deployment', difficulty: 'advanced', type: 'multiple_choice', question: 'What is a reverse proxy?', options: JSON.stringify(['A backward proxy', 'A server that forwards client requests to backend servers', 'A security vulnerability', 'A type of VPN']), correctAnswer: '1', explanation: 'A reverse proxy (nginx, HAProxy) forwards requests, handles SSL, load balancing, and caching.', points: 20, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'deployment', difficulty: 'advanced', type: 'multiple_choice', question: 'What is a load balancer?', options: JSON.stringify(['A weight tool', 'Distributes traffic across multiple servers', 'A database optimization', 'A caching mechanism']), correctAnswer: '1', explanation: 'Load balancers distribute incoming traffic across servers to prevent overload and ensure availability.', points: 20, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'deployment', difficulty: 'advanced', type: 'multiple_choice', question: 'What is Docker Compose?', options: JSON.stringify(['A music tool', 'Tool for defining and running multi-container Docker applications', 'A Docker editor', 'A build tool']), correctAnswer: '1', explanation: 'Docker Compose uses YAML files to define multi-container setups (app, database, cache, etc.).', points: 20, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'deployment', difficulty: 'advanced', type: 'multiple_choice', question: 'What is blue-green deployment?', options: JSON.stringify(['Color coding servers', 'Running two identical environments and switching traffic between them', 'A testing strategy', 'A monitoring tool']), correctAnswer: '1', explanation: 'Blue-green deployment runs two identical environments. Traffic switches from blue (old) to green (new) for zero-downtime.', points: 20, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'deployment', difficulty: 'advanced', type: 'short_answer', question: 'What is the difference between containers and virtual machines?', options: null, correctAnswer: 'Containers share the host OS kernel and are lightweight (MB, seconds to start). VMs include a full OS and hypervisor, are heavier (GB, minutes to start). Containers are more efficient for microservices; VMs provide stronger isolation.', explanation: 'Containers virtualize the OS. VMs virtualize the hardware. Containers are faster and lighter.', points: 25, tags: JSON.stringify(['interview']), source: 'interview' },
];

const generalQuestions = [
  { category: 'general', difficulty: 'beginner', type: 'multiple_choice', question: 'What is a web browser?', options: JSON.stringify(['A search engine', 'Software for accessing and displaying web pages', 'A web server', 'An operating system']), correctAnswer: '1', explanation: 'A browser renders HTML, CSS, and JavaScript to display web pages. Examples: Chrome, Firefox, Safari.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'general', difficulty: 'beginner', type: 'multiple_choice', question: 'What is a web server?', options: JSON.stringify(['A browser', 'Software that serves web content over HTTP', 'A database', 'A domain name']), correctAnswer: '1', explanation: 'A web server receives HTTP requests and returns responses (HTML, JSON, files).', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'general', difficulty: 'beginner', type: 'multiple_choice', question: 'What is HTTP?', options: JSON.stringify(['A programming language', 'HyperText Transfer Protocol - the foundation of web communication', 'A markup language', 'A database protocol']), correctAnswer: '1', explanation: 'HTTP is the protocol for transferring data on the web. HTTPS adds encryption.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'general', difficulty: 'beginner', type: 'multiple_choice', question: 'What is a URL?', options: JSON.stringify(['A programming concept', 'Uniform Resource Locator - an address for a web resource', 'A file type', 'A server name']), correctAnswer: '1', explanation: 'URL is the address used to access resources on the web: protocol://domain:port/path?query#fragment.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'general', difficulty: 'beginner', type: 'multiple_choice', question: 'What is the difference between frontend and backend?', options: JSON.stringify(['No difference', 'Frontend is client-side UI, backend is server-side logic', 'Frontend is the server', 'Backend is the browser']), correctAnswer: '1', explanation: 'Frontend: what users see (HTML, CSS, JS). Backend: server logic, databases, APIs.', points: 10, tags: JSON.stringify(['beginner-friendly']), source: 'interview' },
  { category: 'general', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is an API?', options: JSON.stringify(['A programming language', 'Application Programming Interface - contract for software communication', 'An algorithm', 'A database']), correctAnswer: '1', explanation: 'An API defines how software components interact. RESTful APIs use HTTP methods for web communication.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'general', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is REST?', options: JSON.stringify(['A break from coding', 'Representational State Transfer - architectural style for web services', 'A JavaScript method', 'A database type']), correctAnswer: '1', explanation: 'REST is an architectural style using HTTP methods (GET, POST, PUT, DELETE) for stateless web services.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'general', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is JSON?', options: JSON.stringify(['JavaScript Object Network', 'JavaScript Object Notation - lightweight data interchange format', 'Java Server Objects', 'JS Only Notation']), correctAnswer: '1', explanation: 'JSON is a text-based data format for storing and exchanging structured data.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'general', difficulty: 'intermediate', type: 'multiple_choice', question: 'What is the difference between GET and POST?', options: JSON.stringify(['No difference', 'GET retrieves data (in URL), POST sends data (in body)', 'POST is faster', 'GET sends data in body']), correctAnswer: '1', explanation: 'GET: retrieve data, parameters in URL, cacheable. POST: send data, parameters in body, not cached.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'general', difficulty: 'intermediate', type: 'multiple_choice', question: 'What are HTTP status codes?', options: JSON.stringify(['Error messages', 'Three-digit codes indicating the result of an HTTP request', 'Server names', 'Debug codes']), correctAnswer: '1', explanation: '1xx: Info, 2xx: Success, 3xx: Redirect, 4xx: Client error, 5xx: Server error.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'general', difficulty: 'intermediate', type: 'multiple_choice', question: 'What does status code 404 mean?', options: JSON.stringify(['Server error', 'Not Found - resource does not exist', 'Unauthorized', 'Success']), correctAnswer: '1', explanation: '404 means the requested resource was not found on the server.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'general', difficulty: 'intermediate', type: 'multiple_choice', question: 'What does status code 500 mean?', options: JSON.stringify(['Page not found', 'Internal Server Error', 'Unauthorized', 'Bad Request']), correctAnswer: '1', explanation: '500 indicates an unexpected server error. The server encountered a situation it could not handle.', points: 15, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'general', difficulty: 'advanced', type: 'multiple_choice', question: 'What is a microservices architecture?', options: JSON.stringify(['Small code files', 'Application built as independent, loosely coupled services', 'A JavaScript framework', 'A database design']), correctAnswer: '1', explanation: 'Microservices decompose an application into small, independent services that communicate via APIs.', points: 20, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'general', difficulty: 'advanced', type: 'multiple_choice', question: 'What is a webhook?', options: JSON.stringify(['A fishing hook', 'An HTTP callback - automated notification sent when an event occurs', 'A Git hook', 'A CSS hook']), correctAnswer: '1', explanation: 'Webhooks are HTTP POST requests sent automatically to a URL when a specific event occurs.', points: 20, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'general', difficulty: 'advanced', type: 'multiple_choice', question: 'What is GraphQL?', options: JSON.stringify(['A graphing tool', 'A query language for APIs that lets clients request exactly the data they need', 'A database', 'A JavaScript library']), correctAnswer: '1', explanation: 'GraphQL allows clients to specify exactly what data they need, solving over-fetching and under-fetching.', points: 20, tags: JSON.stringify(['interview']), source: 'interview' },
  { category: 'general', difficulty: 'advanced', type: 'multiple_choice', question: 'What is WebSocket?', options: JSON.stringify(['A power socket', 'A protocol for full-duplex, bidirectional real-time communication', 'A server type', 'An API method']), correctAnswer: '1', explanation: 'WebSocket provides persistent, full-duplex communication between client and server over a single TCP connection.', points: 20, tags: JSON.stringify(['interview']), source: 'interview' },
];

export { nodejsQuestions, databaseQuestions, expressjsQuestions, middlewareQuestions, corsQuestions, deploymentQuestions, generalQuestions };
